name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # specify your node version

      - name: Install dependencies
        run: npm install

      - name: Build Next app
        run: npm run build

      - name: Export static site
        run: npm run build && npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          user_name: ShwetaMate67
          user_email: shwetamate0109@gmail.com
